language: python
python:
  - "2.7"
env:
  - DJANGO=1.5.1 TRAVIS=1
install:
  - sudo apt-get update -q
  - sudo apt-get remove --purge postgresql-9.1-postgis-scripts 
  - sudo apt-get install binutils libproj-dev gdal-bin
  - sudo apt-get install postgresql-9.1-postgis
  - sudo apt-get install python-psycopg2
  - pip install -q Django==$DJANGO
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database event_gis;' -U postgres
  - psql -d event_gis -c 'CREATE EXTENSION postgis;' -U postgres
  - psql -d event_gis -c 'CREATE EXTENSION postgis_topology;' -U postgres
  - python ./event_gis/manage.py syncdb --noinput
script:
  - python ./event_gis/manage.py test
deploy:
  provider: heroku
  api_key: 2126fa8a-3c44-49e8-a60d-4a8b90fa218c
  buildpack:
    - "https://github.com/cyberdelia/heroku-geo-buildpack.git#1.1"
    - "https://github.com/heroku/heroku-buildpack-python.git#v29"
  run:
    - "python event_gis/manage.py syncdb --noinput"