#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

APP_NAME=`cat $OPENSHIFT_REPO_DIR/.app_name`
cd $OPENSHIFT_REPO_DIR/$APP_NAME
APP_WSGI_NAME="${APP_NAME}_live"
$OPENSHIFT_DATA_DIR/bin/uwsgi --enable-threads --socket-protocol http -s $OPENSHIFT_INTERNAL_IP:$OPENSHIFT_INTERNAL_PORT --module $APP_WSGI_NAME.wsgi:application --pp $OPENSHIFT_REPO_DIR/$APP_NAME -d $OPENSHIFT_DIY_LOG_DIR/app.log --pidfile $OPENSHIFT_TMP_DIR/uwsgi.pid
